apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: worker
  name: worker
spec:
  containers:
  - image: dockersamples/examplevotingapp_worker
    name: worker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
